hypertrace/hypertrace-graphql

hypertrace-graphql-service/src/main/resources/configs/common/application.conf

- kube sets default env for service port as <service_name>_port e.g `ATTRIBUTE_SERVICE_PORT. So, we decided to add  `_CONFIG` for app-related host/port config to avoid conflicts.

avoids conflicts between kube envs vs app envs

---

README.md

- Added one line description for GraphQL service.
- Added queries section which lists key queries across main screens including:
- Get all traces in provided time range
- Find trace using TraceID
- Get all services your application is using
- Get all backends your application is using
- Get all API's your application is using
- Get service and backend dependency graph

Adds one line description and key queries in README

---

README.md

- Updated `verify trace exists` as per discussion with @adriancole and @skjindal93 . 
- Removed get list of traces query.

Updates queries in README

---

hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/GraphQlService.java

Observed after updating platform service framework dependency

fix: NPE for service name getter

---

.snyk

Ignore it in .snyk file since there is no patch for it

fix: snyk ionetty vulberability warning

---

hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlFactory.java
hypertrace-graphql-service/build.gradle.kts

Update most depenedncies, including vulnerabilities
Unit testing and local e2e query.

chore: bump dependencies

---

hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/argument/ExplorerScopeArgument.java

This was a typo in the explorer api's arg names that hadn't been hit yet because the UI still uses the deprecated path.
Manually verified the corrected name works

fix: switch typo in explorer scope arg 'string' -> 'scope'

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/schema/Entity.java
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/schema/EntitySchema.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/dao/GatewayServiceExploreResponseConverter.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/deserialization/GroupByArgumentDeserializationConfig.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/DefaultExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/ExploreResult.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/ExplorerSchema.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/argument/GroupByArgument.java

Remove previously deprecated code that is no longer in use via the UI (and hasn't been for at least 2 months). Deprecate more code (alternatives have been added, but UI has not yet been updated). This is the second part of https://github.com/hypertrace/hypertrace-core-graphql/pull/45 , and depends on that PR.
Verified unit tests, UI code, ran HT e2e with change and verified no issues.

chore: remove unused deprecated code, deprecate more

---

hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/ConfigServiceSpacesConfigDao.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/SpaceConfigRulesRequestConverter.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/SpaceConfigRulesResponseConverter.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/SpacesConfigDao.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/deserialization/SpaceConfigRuleDeserializationConfig.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/deserialization/SpaceRuleIdArgument.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/deserialization/SpacesDeserializationModule.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/mutator/SpaceConfigRuleDeleteMutator.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/mutator/SpaceConfigRuleUpdateMutator.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/request/SpaceConfigRequestBuilder.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/request/SpaceConfigRequestBuilderImpl.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/request/SpaceConfigRuleDeleteRequest.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/request/SpaceConfigRuleUpdateRequest.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/schema/mutation/SpacesMutationSchema.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/schema/shared/SpaceConfigRule.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/dao/SpaceConfigRulesRequestConverterTest.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/dao/SpaceConfigRulesResponseConverterTest.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/deserialization/SpaceConfigRuleDeserializationConfigTest.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/request/SpaceConfigRequestBuilderImplTest.java

This change adds support for updtaing and deleting space config rules in support of hypertrace/hypertrace#142 .
This has been verified E2E and unit tests have been added for code with non-trivial logic.

Space rules update and delete

---

hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/ExplorerBackedSpacesDao.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/dao/ExplorerBackedSpacesDaoTest.java

This was misimplemented - the expectation is the list of spaces should be alphabetical i.e. "A" -> "B", which corresponds to ascending ordering.

fix: reverse space ordering to be sorted asc

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayBaselineDao.java
hypertrace-graphql-gateway-service-metric-utils/src/main/java/org/hypertrace/graphql/utils/metrics/gateway/MetricContainerMapConverter.java

Baseline metric currently tightly coupled with metric series request, baseline values will be obtained only when corresponding metric series data present. With this change both are decoupled, graphql query will retrieve only baseline series without metric series in it. 
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Decouple metric series requests and baseline series requests

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayServiceEntityRequestBuilder.java
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/request/DefaultEntityRequestBuilder.java
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/request/EntityRequest.java
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/request/NeighborEntitiesRequestBuilder.java

Setting `fetchTotal` on EntitiesRequest, only if the `total` has been requested

perf(entities): set fetch total flag, if requested

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlFactory.java
hypertrace-graphql-platform/build.gradle.kts
hypertrace-graphql-service/build.gradle.kts
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/resources/configs/common/application.conf
settings.gradle.kts

Update to latest deps to clear out newer vulns
Unit, ran e2e

chore: update dependencies

---

hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/dao/GatewayServiceExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/deserialization/GroupByArgumentDeserializationConfig.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/DefaultExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/ExploreRequest.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/argument/GroupByArgument.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/ExplorerBackedSpacesDao.java

Expose optional group limit api parameter for explorer
Verified behavior E2E

feat: add group limit to explorer api

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/joiner/DefaultEntityJoinerBuilder.java

Recently, gateway service stopped returning results for recent time ranges, even when includeActive is true. This extends the time range on the entity join even though we don't use the time range until the gateway issue can be addressed.
Verified E2E

fix: work around time agnostic query issue

---

hypertrace-graphql-service/build.gradle.kts

- Incorporate the latest changes from hypertrace-core-graphql submodule

chore: update submodule reference to latest

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayBaselineDao.java
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayServiceEntityDao.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/dao/GatewayServiceExplorerDao.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java

These changes are in context of: hypertrace/hypertrace-core-graphql#69. Currently, we hardcode the deadline as 10s. Now, GATEWAY_SERVICE_DEADLINE is read from application.conf
Deployed and tested the application manually. I am still seeing if I can write a UT for check if config value is being loaded properly. 
This PR is dependent on: https://github.com/hypertrace/hypertrace-service/pull/99

Gateway-Service Client Timeout Config

---

.snyk
hypertrace-graphql-service-config/src/main/java/org/hypertrace/graphql/config/HypertraceGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/ConfigServiceSpacesConfigDao.java

Like the PR [here](https://github.com/hypertrace/hypertrace-graphql/pull/91/files), this change is to make client timeout for the Attribute Service configurable.
Deployed and tested the application locally. Scenarios:
1. Missing config: Default timeout is used.
2. Timeout configured: Configured value is used.

Entity Service and Config Service Configurable Timeouts

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/request/DefaultEntityRequestBuilder.java

The labels attribute was getting requested from attribute for an entity, even though the `labels` field wasn't requested in the selection set, leading to missing `labels` attribute errors for entity type for which the `labels` attribute doesn't exist

fix(entity): query labels attribute, if requested

---

hypertrace-graphql-metric-schema/src/main/java/org/hypertrace/graphql/metric/request/MetricArguments.java

Ref issue : https://github.com/hypertrace/hypertrace/issues/314#

AVGRATE changes 

---

hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/dao/LabelRequestConverter.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/dao/LabelResponseConverter.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/deserialization/CreateLabelDeserializationConfig.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/deserialization/LabelDeserializationConfig.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/request/LabelRequestBuilderImpl.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/Label.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/LabelData.java
hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/mutation/CreateLabel.java

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Adding color, description in labels graphql apis

---

hypertrace-graphql-label-application-rules-schema/src/main/java/org/hypertrace/graphql/label/application/rules/dao/LabelApplicationRuleRequestConverter.java
hypertrace-graphql-label-application-rules-schema/src/main/java/org/hypertrace/graphql/label/application/rules/dao/LabelApplicationRuleResponseConverter.java
hypertrace-graphql-label-application-rules-schema/src/main/java/org/hypertrace/graphql/label/application/rules/deserialization/LabelApplicationRuleDataDeserializationConfig.java
hypertrace-graphql-label-application-rules-schema/src/main/java/org/hypertrace/graphql/label/application/rules/deserialization/LabelApplicationRuleDeserializationConfig.java
hypertrace-graphql-label-application-rules-schema/src/main/java/org/hypertrace/graphql/label/application/rules/schema/shared/LabelApplicationRuleData.java
hypertrace-graphql-platform/build.gradle.kts

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

Adding enabled, description fields to label application rules

---

helm/templates/serviceconfig.yaml
helm/values.yaml
hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlFactory.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/GraphQlServiceImpl.java
hypertrace-graphql-service/src/main/resources/configs/common/application.conf

Adds support for configuring query timeout (defaulting to current value)

feat: add support for configuring query timeout

---

hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/DefaultExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/ExploreRequestBuilder.java

Explore API is now being used as part of other APIs too (like events) which do not inherently support many of the functionalities that explore does..
One requirement is to build the request using pre-defined scope and manipulating the arguments instead of using the user-entered arguments as is.
Hence, added an overloaded build method which takes all the arguments as parameters.

Added build method for explore-request-builder

---

.snyk

Updated hypertrace-graphql-core submodule

Updated submodule

---

hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/dao/GatewayServiceExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/DefaultExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/ExploreRequest.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/ExploreRequestBuilder.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/schema/ExplorerSchema.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/dao/ExplorerBackedSpacesDao.java
hypertrace-graphql-spaces-schema/src/test/java/org/hypertrace/graphql/spaces/dao/ExplorerBackedSpacesDaoTest.java

Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

make time range optional in explore query

---

helm/templates/serviceconfig.yaml
helm/values.yaml
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/resources/configs/common/application.conf

See https://github.com/hypertrace/hypertrace-core-graphql/pull/102

feat: add parallel querying

---

.github/workflows/pr-test.yml
.snyk
hypertrace-graphql-impl/build.gradle.kts
hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlFactory.java
hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlModule.java
hypertrace-graphql-impl/src/test/java/org/hypertrace/graphql/impl/GraphQlModuleTest.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/GraphQlServiceFactory.java

Consume refactor to use the container's channel registry rather than building our own internally
Depends on https://github.com/hypertrace/hypertrace-core-graphql/pull/106

refactor: use container provided channel registry

---

hypertrace-graphql-platform/build.gradle.kts
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/dao/ConfigServiceSpanProcessingRequestConverter.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/dao/ConfigServiceSpanProcessingRuleConverter.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/deserialization/ExcludeSpanCreateInputDeserializationConfig.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/schema/rule/ExcludeSpanRuleInfo.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/schema/rule/ExcludeSpanRuleRuleType.java

This PR adds the rule type field for exclude span rules to distinguish between system exclude span rules and user exclude span rules. Depends on https://github.com/hypertrace/config-service/pull/133.

chore: update exclude span rule schema

---

.github/workflows/merge-publish.yml
.github/workflows/pr-build.yml
.github/workflows/pr-test.yml
.github/workflows/publish.yml
build.gradle.kts
owasp-suppressions.xml

Update CI workflows to
- use newer runners
- use latest action versions
- remove redundant caching (now built into gradle actions)
- remove redundant check in build job (moved all verification into test job which was already running tests)
- replace snyk scan with owasp-based hypertrace action

ci: update gha config to use newer versions and actions

---

hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/fetcher/EntityFetcher.java
hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/fetcher/ExplorerFetcher.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/fetcher/LabelApplicationRuleFetcher.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/fetcher/LabelFetcher.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/mutator/LabelApplicationRuleCreateMutator.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/mutator/LabelApplicationRuleDeleteMutator.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/mutator/LabelApplicationRuleUpdateMutator.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/mutator/LabelCreateMutator.java
hypertrace-graphql-labels-schema-api/src/main/java/org/hypertrace/graphql/label/mutator/LabelUpdateMutator.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/fetcher/SpaceConfigRuleFetcher.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/fetcher/SpacesFetcher.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/mutator/SpaceConfigRuleCreationMutator.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/mutator/SpaceConfigRuleDeleteMutator.java
hypertrace-graphql-spaces-schema/src/main/java/org/hypertrace/graphql/spaces/mutator/SpaceConfigRuleUpdateMutator.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/fetcher/mutation/ExcludeSpanCreateRuleMutator.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/fetcher/mutation/ExcludeSpanDeleteRuleMutator.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/fetcher/mutation/ExcludeSpanUpdateRuleMutator.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/fetcher/query/ExcludeSpanRulesFetcher.java

Requires https://github.com/hypertrace/hypertrace-core-graphql/pull/135 - see for more info.

refactor: update direct use of context to use new version

---

hypertrace-graphql-entity-schema/build.gradle.kts
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayServiceEntityDao.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/resources/configs/common/application.conf

Depends on https://github.com/hypertrace/hypertrace-core-graphql/pull/141

chore(gateway-service): configurable max channel inbound message size

---

hypertrace-graphql-platform/build.gradle.kts
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/dao/ConfigServiceSpanFilterConverter.java
hypertrace-graphql-span-processing-schema/src/main/java/org/hypertrace/graphql/spanprocessing/schema/rule/filter/SpanProcessingRelationalOperator.java

This PR adds for not contains span filter operator.

chore: add support for does not contain span filter operator

---

hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlFactory.java
hypertrace-graphql-impl/src/main/java/org/hypertrace/graphql/impl/GraphQlModule.java
hypertrace-graphql-impl/src/test/java/org/hypertrace/graphql/impl/GraphQlModuleTest.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlEndpointConfig.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-graphql-service/src/main/java/org/hypertrace/graphql/service/GraphQlServiceFactory.java
hypertrace-graphql-service/src/main/resources/configs/common/application.conf

chore: disable introspection by default

---

hypertrace-graphql-gateway-service-metric-utils/src/main/java/org/hypertrace/graphql/utils/metrics/gateway/AggregatableOrderByExpressionListConverter.java
hypertrace-graphql-gateway-service-metric-utils/src/main/java/org/hypertrace/graphql/utils/metrics/gateway/GatewayMetricUtilsModule.java
hypertrace-graphql-gateway-service-metric-utils/src/main/java/org/hypertrace/graphql/utils/metrics/gateway/MetricAggregationExpressionConverter.java

This is a bandaid for a gateway service bug that requires a more involved fix. Gateway service makes an assumption that the alias for an order by expression will match the column it's ordering by when being applied in memory such as an entity-explorer query. We should break that assumption, but for now abiding by it by using the same alias generation code.

fix: send alias on order by expression

---

hypertrace-graphql-entity-schema/build.gradle.kts
hypertrace-graphql-entity-schema/src/main/java/org/hypertrace/graphql/entity/dao/GatewayServiceEntityDao.java

Add support for `apiFilters` for `filteredDataSpecs`. Entity query transformation was missing the request transformation to transform the request based on the `apiFilters` in `filteredDataSpecs`

fix(entities): support for API filters for filtered data specs

---

hypertrace-graphql-explorer-schema/src/main/java/org/hypertrace/graphql/explorer/request/ExploreSelectionRequestBuilder.java
hypertrace-graphql-metric-schema/src/main/java/org/hypertrace/graphql/metric/request/DefaultMetricAggregationRequestBuilder.java
hypertrace-graphql-metric-schema/src/main/java/org/hypertrace/graphql/metric/request/MetricAggregationRequestBuilder.java

Reverts hypertrace/hypertrace-graphql#235

chore | revert passing the alias in case of aggregations and create default alias without dot
